### ISSUE TITLE
身份验证不了

### ISSUE THREAD

**Issue by qmlCoder** [leostrong8/openai-fill-billing#1]
身份验证上传身份证的时候老是显示 KYC System Maintenance
![Screenshot_2023-04-07-22-38-21-330_com ukde bacpa](https://user-images.githubusercontent.com/88520934/230708048-7ffb4913-b463-432b-a1e8-4814feca8bee.jpg)

**Comment by leostrong8** [comment]
> 身份验证上传身份证的时候老是显示 KYC System Maintenance ![Screenshot_2023-04-07-22-38-21-330_com ukde bacpa](https://user-images.githubusercontent.com/88520934/230708048-7ffb4913-b463-432b-a1e8-4814feca8bee.jpg)

身份信息都如实填写了嘛？

**Comment by qmlCoder** [comment]
填写了，文本都可以填写，就是身份证图片上传不了&nbsp;


石小飞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月8日(星期六) 晚上9:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leostrong8/openai-fill-billing] 身份验证不了 (Issue #1)





  
身份验证上传身份证的时候老是显示 KYC System Maintenance 
  
身份信息都如实填写了嘛？

**Comment by leostrong8** [comment]
> 身份验证上传身份证的时候老是显示 KYC System Maintenance ![Screenshot_2023-04-07-22-38-21-330_com ukde bacpa](https://user-images.githubusercontent.com/88520934/230708048-7ffb4913-b463-432b-a1e8-4814feca8bee.jpg)

那就是系统维护，你等等再试一下，

**Comment by leostrong8** [comment]
close
